---
title: "EDA"
author: "Yuchen Huang"
date: "2023-11-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(lme4)
library(rstanarm)
library(coefplot)
set.seed(678)

suicide <- read.csv("master.csv")
hdi <- read.csv("HDR21-22_Composite_indices_complete_time_series.csv")
hdi$country[hdi$country == "Korea (Republic of)"] <- "Republic of Korea"
```

$$
HDI = (\frac{LE-20}{85-20}\times\frac{MYSI+EYSI}{2}\times\frac{ln(GNIpc)-ln(100)}{ln(20,000)-ln(100)})^{\frac{1}{3}}
$$

## Data Cleaning

```{r}
##get only hdi from the data
HDI <- hdi |>
  select(country, starts_with("hdi_")) |>
  select(-hdi_rank_2021)

## remove NA
HDI <- HDI |>
  filter(is.na(hdi_1990)==F)

## remove hdi in the column names
colnames(HDI) <- gsub("hdi_", "", colnames(HDI)) 
HDI <- HDI |> select(-starts_with("f"), -starts_with("m"))

## convert HDI into long format
HDI_long <- HDI |>
  pivot_longer(cols = -country, names_to = "year", values_to = "HDI")

## select suicide data after 1990
suicide <- suicide |>
  filter(year >= 1990)
HDI_long$year <- as.integer(HDI_long$year)

## combine HDI_long and suicide together
Suicide <- suicide |>
  left_join(HDI_long, by = c("country", "year")) |>
  mutate(HDI = HDI)
Suicide <- Suicide |>
  select(-HDI.for.year) |>
  relocate(HDI, .before = gdp_for_year....)

## check how many lines HDI is NA
Suicide_clean <- Suicide |>
  filter(is.na(HDI)==F)
#unique(Suicide_na$country)
paste0("There are ",length(unique(Suicide_clean$country))," countries in the data set")
```

Add LE

```{r}
##Add Life Expectancy, MYSI, EYSI, GNI per capita
LE <- hdi |>
  select(country, starts_with("le_19"), starts_with("le_20"))

colnames(LE) <- gsub("le_", "", colnames(LE))

LE <- LE |>
  filter(is.na(`1990`)==F)

LE_long <- LE |>
  pivot_longer(cols = -country, names_to = "year", values_to = "LE")

LE_long$year <- as.integer(LE_long$year)

Suicide_clean <- Suicide_clean |>
  left_join(LE_long, by = c("country", "year")) |>
  mutate(LE = LE)|>
  relocate(LE, .before = gdp_for_year....)

```

Add MYSI and EYSI

```{r}
EYS <- hdi |>
  select(country, starts_with("eys_19"), starts_with("eys_20"))
colnames(EYS) <- gsub("eys_", "", colnames(EYS))
EYS <- EYS |>
  filter(is.na(`1990`)==F)

EYS_long <- EYS |>
  pivot_longer(cols = -country, names_to = "year", values_to = "EYS")
EYS_long$year <- as.integer(EYS_long$year)

Suicide_clean <- Suicide_clean |>
  left_join(EYS_long, by = c("country", "year")) |>
  mutate(EYS = EYS) |>
  relocate(EYS, .before = gdp_for_year....)

MYS <- hdi |>
  select(country, starts_with("mys_19"), starts_with("mys_20"))
colnames(MYS) <- gsub("mys_", "", colnames(MYS))
MYS <- MYS |>
  filter(is.na(`1990`)==F)

MYS_long <- MYS |>
  pivot_longer(cols = -country, names_to = "year", values_to = "MYS")
MYS_long$year <- as.integer(MYS_long$year)

Suicide_clean <- Suicide_clean |>
  left_join(MYS_long, by = c("country", "year")) |>
  mutate(MYS = MYS) |>
  relocate(MYS, .before = gdp_for_year....)
```

Add GNI per Capita

```{r}
GNI <- hdi |>
  select(country, starts_with("gnipc_19"), starts_with("gnipc_20"))
colnames(GNI) <- gsub("gnipc_", "", colnames(GNI))
GNI <- GNI |>
  filter(is.na(`1990`)==F)

GNI_long <- GNI |>
  pivot_longer(cols = -country, names_to = "year", values_to = "GNI")
GNI_long$year <- as.integer(GNI_long$year)

Suicide_clean <- Suicide_clean |>
  left_join(GNI_long, by = c("country", "year")) |>
  mutate(GNI = GNI) |>
  relocate(GNI, .before = gdp_for_year....)

```

```{r, echo = FALSE, warning = FALSE}
Suicide_clean <- Suicide_clean |>
  select(-country.year, -gdp_for_year...., suicides_no, -age)
## cleaning environment
rm(hdi, HDI, HDI_long) 
rm(suicide, Suicide, Suicide_na)
rm(LE, LE_long)
rm(MYS, MYS_long, EYS, EYS_long)
rm(GNI, GNI_long)
```

Convert all the input in a roughly same scale

```{r}
Suicide_clean$LE <- (Suicide_clean$LE-20)/(85-20)
Suicide_clean$EI <- (Suicide_clean$MYS+Suicide_clean$EYS)/2
Suicide_clean$GNI <- (log(Suicide_clean$GNI)-log(100))/(log(20000)-log(100))
Suicide_clean$population <-  Suicide_clean$population/100000
Suicide_clean$gdp_per_capita.... <- log(Suicide_clean$gdp_per_capita....)/10

Suicide_clean <- Suicide_clean |>
  relocate(EI, .after = LE) |>
  select(-MYS, -EYS)
```

## EDA

```{r}
Suicide_clean |>
  ggplot(mapping = aes(HDI,(suicides.100k.pop))) +
  geom_boxplot(aes(fill = sex), outlier.color = "red", outlier.shape = 16)
```

```{r}
Suicide_clean |>
  ggplot() +
  aes(x = HDI, y = suicides.100k.pop, color = sex) +
  geom_point(size = .5)
```

```{r}
Suicide_clean |> 
  subset(country %in% sample(Suicide_clean$country, 12)) |>
  ggplot() +
  aes(x = year, y = suicides.100k.pop, color = generation) +
  geom_point(size = .5) +
  facet_wrap(~country)
```

## Model

six models

#### Null Model

-   model

```{r}
null_model <- mean(Suicide_clean$suicides.100k.pop)
```

-   Prediction and Plot

```{r}
null_pred <- Suicide_clean |> select(country, suicides.100k.pop)
null_pred$predict <- rep(null_model, times = nrow(Suicide_clean))
null_pred$resid <- null_pred$suicides.100k.pop -null_pred$predict

ggplot(null_pred, aes(x = predict, y = resid)) +
  geom_point() +
  geom_hline(yintercept = 0, linetype = "dashed", color = "red") +
  labs(title = "Residual Plot of Null Mofrl", x = "Predicted Suicide Rate", y = "Residuals") +
  theme_minimal()
```

#### Complete Pooling

```{r}
comp_model <- Suicide_clean |>
  lm(formula = suicides.100k.pop ~ year + sex + population + HDI + LE + EI + GNI + gdp_per_capita.... + generation + country)
summary(comp_model)
paste0("R squared is 0.5298")
```

```{r}
plot(comp_model,which =1)
```

#### Partial Pooling

```{r, warning=F}
partial_model <- Suicide_clean |>
  lmer(formula = suicides.100k.pop ~ year + sex + population + HDI + LE + EI + GNI + gdp_per_capita.... + generation + (1|country))
#summary(partial_model)

```

-   plot

```{r}
coefplot(partial_model, title = "")

partial_pred <- Suicide_clean |> select(country, suicides.100k.pop)
partial_pred$predicted_suicide_rate <- predict(partial_model, newdata = Suicide_clean)
partial_pred$predicted_suicide_rate <- ifelse(partial_pred$predicted_suicide_rate<=0, 0, partial_pred$predicted_suicide_rate)

partial_pred$residuals <- partial_pred$suicides.100k.pop - partial_pred$predicted_suicide_rate

partial_pred |>
  ggplot(aes(x = predicted_suicide_rate, y = residuals)) +
  geom_point() +
  geom_hline(yintercept = 0, linetype = "dashed", color = "red") +
  labs(title = "Residual Plot of partial pooling", x = "Predicted Suicide Rate", y = "Residuals") +
  theme_minimal()


```

```{r}
selected_countries <- sample(unique(Suicide_clean$country), 12)

selected_data <- Suicide_clean |>
  filter(country %in% selected_countries)

partial_model_selected <- lmer(suicides.100k.pop ~ year + sex + population + HDI + LE + EI + GNI + gdp_per_capita.... + generation + (1|country), data = selected_data)

fixef_estimates_selected <- fixef(partial_model_selected)
ranef_estimates_selected <- ranef(partial_model_selected)$country

country_intercepts_selected <- data.frame(country = rownames(ranef_estimates_selected), intercept = ranef_estimates_selected[, "(Intercept)"])

plot_data_selected <- selected_data |>
  left_join(country_intercepts_selected, by = "country")

ggplot(plot_data_selected, aes(x = year, y = suicides.100k.pop, group = country)) +
  geom_point(aes(color = generation), size = 0.5) +
  geom_line(aes(y = intercept + fixef_estimates_selected["year"] * year), color = "blue", size = 0.5) +
  facet_wrap(~country) +
  labs(title = "Varying Intercept with Shared Slope for Selected Countries") +
  theme_minimal()
```

#### No Pooling

```{r}
no_model <- Suicide_clean |>
  split(.$country) |>
  lapply(function(df) {
    lm(suicides.100k.pop ~ year + sex + population + HDI + LE + EI + GNI + gdp_per_capita.... + generation, data = df)
  })
no_model[1]
length(no_model)
```

```{r}
Suicide_clean |> 
  subset(country %in% sample(Suicide_clean$country, 12)) |>
  ggplot() +
  aes(x = year, y = suicides.100k.pop, color = generation) +
  geom_point(size = .5) +
  facet_wrap(~country) +
  geom_smooth(method = "lm", color = "blue", linewidth = .5)
```

#### 

## Countries

```{r}
Suicide_clean |> 
  subset(country %in% sample(Suicide_clean$country, 12)) |>
  ggplot() +
  aes(x = year, y = suicides.100k.pop, color = generation) +
  geom_point(size = .5) +
  facet_wrap(~country)
```

```{r}
Suicide_clean |> 
  subset(country %in% sample(Suicide_clean$country, 12)) |>
  ggplot() +
  aes(x = year, y = suicides.100k.pop, color = generation) +
  geom_point(size = .5) +
  facet_wrap(~country)
```

```{r}
Suicide_clean |> 
  subset(country %in% sample(Suicide_clean$country, 12)) |>
  ggplot() +
  aes(x = year, y = suicides.100k.pop, color = generation) +
  geom_point(size = .5) +
  facet_wrap(~country) +
  geom_smooth(method = "lm", color = "blue", size = .5)
```

## United State

```{r}
suicide_US <- suicide |>
  filter(country == "United States")
```

## Reference

[Human Development Reports](https://hdr.undp.org/data-center/documentation-and-downloads)
